### DuckDB vs Pandas for READ operations

In [1]:
import duckdb
import pandas as pd

In [2]:
# Pandas processes the entire database inside the computer's RAM memory. 
# For large databases, it can take up a big amount of the local's machine space. 

df = pd.read_csv('/Users/julianasampar/Desktop/learning_dev/personal_dev/pyprojects/others/archive/Amazon Customer Behavior Survey.csv')
display(df)

,Timestamp,age,Gender,Purchase_Frequency,Purchase_Categories,Personalized_Recommendation_Frequency,Browsing_Frequency,Product_Search_Method,Search_Result_Exploration,Customer_Reviews_Importance,...,Saveforlater_Frequency,Review_Left,Review_Reliability,Review_Helpfulness,Personalized_Recommendation_Frequency,Recommendation_Helpfulness,Rating_Accuracy,Shopping_Satisfaction,Service_Appreciation,Improvement_Areas
0,2023/06/04 1:28:19 PM GMT+5:30,23,Female,Few times a month,Beauty and Personal Care,Yes,Few times a week,Keyword,Multiple pages,1,...,Sometimes,Yes,Occasionally,Yes,2,Yes,1,1,Competitive prices,Reducing packaging waste
1,2023/06/04 2:30:44 PM GMT+5:30,23,Female,Once a month,Clothing and Fashion,Yes,Few times a month,Keyword,Multiple pages,1,...,Rarely,No,Heavily,Yes,2,Sometimes,3,2,Wide product selection,Reducing packaging waste
2,2023/06/04 5:04:56 PM GMT+5:30,24,Prefer not to say,Few times a month,Groceries and Gourmet Food;Clothing and Fashion,No,Few times a month,Keyword,Multiple pages,2,...,Rarely,No,Occasionally,No,4,No,3,3,Competitive prices,Product quality and accuracy
3,2023/06/04 5:13:00 PM GMT+5:30,24,Female,Once a month,Beauty and Personal Care;Clothing and Fashion;...,Sometimes,Few times a month,Keyword,First page,5,...,Sometimes,Yes,Heavily,Yes,3,Sometimes,3,4,Competitive prices,Product quality and accuracy
4,2023/06/04 5:28:06 PM GMT+5:30,22,Female,Less than once a month,Beauty and Personal Care;Clothing and Fashion,Yes,Few times a month,Filter,Multiple pages,1,...,Rarely,No,Heavily,Yes,4,Yes,2,2,Competitive prices,Product quality and accuracy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
597,2023/06/12 4:02:02 PM GMT+5:30,23,Female,Once a week,Beauty and Personal Care,Sometimes,Few times a week,categories,Multiple pages,4,...,Sometimes,Yes,Moderately,Sometimes,3,Sometimes,3,4,Competitive prices,Customer service responsiveness
598,2023/06/12 4:02:53 PM GMT+5:30,23,Female,Once a week,Clothing and Fashion,Sometimes,Few times a week,Filter,Multiple pages,3,...,Sometimes,Yes,Heavily,Sometimes,3,Sometimes,3,3,Product recommendations,Reducing packaging waste
599,2023/06/12 4:03:59 PM GMT+5:30,23,Female,Once a month,Beauty and Personal Care,Sometimes,Few times a week,categories,Multiple pages,3,...,Sometimes,Yes,Occasionally,Sometimes,3,Sometimes,2,3,Wide product selection,Product quality and accuracy
600,2023/06/12 9:57:20 PM GMT+5:30,23,Female,Few times a month,Beauty and Personal Care;Clothing and Fashion;...,Yes,Few times a month,Keyword,Multiple pages,1,...,Sometimes,No,Heavily,Yes,2,Yes,2,2,Wide product selection,Product quality and accuracy
601,2023/06/16 9:16:05 AM GMT+5:30,23,Female,Once a week,Clothing and Fashion,Sometimes,Multiple times a day,Keyword,Multiple pages,3,...,Sometimes,Yes,Moderately,Sometimes,3,Sometimes,3,3,Product recommendations,Product quality and accuracy

In [3]:
# DuckDB is a database that allows to read massive databases and faster.
# It identifies the chunk of local memory space and automatically stream the process into batches.
# DuckDB can read csv, parquet and etc files and perform SQL queries on top of it.

db = duckdb.sql("SELECT * FROM '/Users/julianasampar/Desktop/learning_dev/personal_dev/pyprojects/others/archive/Amazon Customer Behavior Survey.csv' ")
display(db)

┌────────────────────────────────┬───────┬───────────────────┬────────────────────────┬──────────────────────────────────────────────────────┬───────────────────────────────────────┬──────────────────────┬───────────────────────┬───────────────────────────┬─────────────────────────────┬──────────────────────┬───────────────────────────┬────────────────────────────────────────────┬────────────────────────┬─────────────┬────────────────────┬────────────────────┬─────────────────────────────────────────┬────────────────────────────┬─────────────────┬───────────────────────┬─────────────────────────┬─────────────────────────────────┐
│           Timestamp            │  age  │      Gender       │   Purchase_Frequency   │                 Purchase_Categories                  │ Personalized_Recommendation_Frequency │  Browsing_Frequency  │ Product_Search_Method │ Search_Result_Exploration │ Customer_Reviews_Importance │ Add_to_Cart_Browsing │ Cart_Completion_Frequency │          Cart_Abandonment_Factors          │ Saveforlater_Frequency │ Review_Left │ Review_Reliability │ Review_Helpfulness │ Personalized_Recommendation_Frequency_1 │ Recommendation_Helpfulness │ Rating_Accuracy │ Shopping_Satisfaction │  Service_Appreciation   │        Improvement_Areas        │
│            varchar             │ int64 │      varchar      │        varchar         │                       varchar                        │                varchar                │       varchar        │        varchar        │          varchar          │            int64            │       varchar        │          varchar          │                  varchar                   │        varchar         │   boolean   │      varchar       │      varchar       │                  int64                  │          varchar           │      int64      │         int64         │         varchar         │             varchar             │
├────────────────────────────────┼───────┼───────────────────┼────────────────────────┼──────────────────────────────────────────────────────┼───────────────────────────────────────┼──────────────────────┼───────────────────────┼───────────────────────────┼─────────────────────────────┼──────────────────────┼───────────────────────────┼────────────────────────────────────────────┼────────────────────────┼─────────────┼────────────────────┼────────────────────┼─────────────────────────────────────────┼────────────────────────────┼─────────────────┼───────────────────────┼─────────────────────────┼─────────────────────────────────┤
│ 2023/06/04 1:28:19 PM GMT+5:30 │    23 │ Female            │ Few times a month      │ Beauty and Personal Care                             │ Yes                                   │ Few times a week     │ Keyword               │ Multiple pages            │                           1 │ Yes                  │ Sometimes                 │ Found a better price elsewhere             │ Sometimes              │ true        │ Occasionally       │ Yes                │                                       2 │ Yes                        │               1 │                     1 │ Competitive prices      │ Reducing packaging waste        │
│ 2023/06/04 2:30:44 PM GMT+5:30 │    23 │ Female            │ Once a month           │ Clothing and Fashion                                 │ Yes                                   │ Few times a month    │ Keyword               │ Multiple pages            │                           1 │ Yes                  │ Often                     │ High shipping costs                        │ Rarely                 │ false       │ Heavily            │ Yes                │                                       2 │ Sometimes                  │               3 │                     2 │ Wide product selection  │ Reducing packaging waste        │
│ 2023/06/04 5:04:56 PM GMT+5:30 │    24 │ Prefer not to say │ Few times a month      │ Groceries and Gourmet Food;Clothing and Fashion      │ No                                    │ Few times a month    │ Keyword               │ Multiple pages            │                           2 │ Yes                  │ Sometimes                 │ Found a better price elsewhere             │ Rarely                 │ false       │ Occasionally       │ No                 │                                       4 │ No                         │               3 │                     3 │ Competitive prices      │ Product quality and accuracy    │
│ 2023/06/04 5:13:00 PM GMT+5:30 │    24 │ Female            │ Once a month           │ Beauty and Personal Care;Clothing and Fashion;others │ Sometimes                             │ Few times a month    │ Keyword               │ First page                │                           5 │ Maybe                │ Sometimes                 │ Found a better price elsewhere             │ Sometimes              │ true        │ Heavily            │ Yes                │                                       3 │ Sometimes                  │               3 │                     4 │ Competitive prices      │ Product quality and accuracy    │
│ 2023/06/04 5:28:06 PM GMT+5:30 │    22 │ Female            │ Less than once a month │ Beauty and Personal Care;Clothing and Fashion        │ Yes                                   │ Few times a month    │ Filter                │ Multiple pages            │                           1 │ Yes                  │ Sometimes                 │ High shipping costs                        │ Rarely                 │ false       │ Heavily            │ Yes                │                                       4 │ Yes                        │               2 │                     2 │ Competitive prices      │ Product quality and accuracy    │
│ 2023/06/04 6:01:59 PM GMT+5:30 │    21 │ Female            │ Less than once a month │ Clothing and Fashion                                 │ No                                    │ Rarely               │ categories            │ Multiple pages            │                           1 │ Yes                  │ Rarely                    │ Changed my mind or no longer need the item │ Never                  │ false       │ Heavily            │ Yes                │                                       5 │ No                         │               5 │                     2 │ Wide product selection  │ Product quality and accuracy    │
│ 2023/06/04 6:31:41 PM GMT+5:30 │    22 │ Female            │ Less than once a month │ Clothing and Fashion                                 │ No                                    │ Rarely               │ Filter                │ Multiple pages            │                           1 │ Yes                  │ Often                     │ High shipping costs                        │ Rarely                 │ false       │ Heavily            │ Yes                │                                       3 │ Sometimes                  │               3 │                     3 │ Wide product selection  │ Shipping speed and reliability  │
│ 2023/06/04 7:13:12 PM GMT+5:30 │    21 │ Female            │ Few times a month      │ Beauty and Personal Care;Clothing and Fashion        │ No                                    │ Rarely               │ Keyword               │ Multiple pages            │                           1 │ Yes                  │ Often                     │ Found a better price elsewhere             │ Rarely                 │ false       │ Heavily            │ Sometimes          │                                       3 │ Sometimes                  │               1 │                     3 │ Competitive prices      │ Shipping speed and reliability  │
│ 2023/06/04 7:23:21 PM GMT+5:30 │    20 │ Female            │ Less than once a month │ Beauty and Personal Care;Clothing and Fashion        │ Sometimes                             │ Few times a month    │ Keyword               │ First page                │                           1 │ Yes                  │ Sometimes                 │ Changed my mind or no longer need the item │ Often                  │ false       │ Moderately         │ Yes                │                                       2 │ Yes                        │               2 │                     2 │ Wide product selection  │ Reducing packaging waste        │
│ 2023/06/04 7:33:12 PM GMT+5:30 │    23 │ Female            │ Less than once a month │ Beauty and Personal Care;Clothing and Fashion        │ No                                    │ Rarely               │ Keyword               │ Multiple pages            │                           1 │ Yes                  │ Rarely                    │ Found a better price elsewhere             │ Rarely                 │ false       │ Heavily            │ Yes                │                                       3 │ Yes                        │               3 │                     4 │ Wide product selection  │ Product quality and accuracy    │
│               ·                │     · │   ·               │           ·            │            ·                                         │ ·                                     │   ·                  │    ·                  │       ·                   │                           · │  ·                   │   ·                       │               ·                            │   ·                    │  ·          │    ·               │  ·                 │                                       · │  ·                         │               · │                     · │         ·               │              ·                  │
│               ·                │     · │   ·               │           ·            │            ·                                         │ ·                                     │   ·                  │    ·                  │       ·                   │                           · │  ·                   │   ·                       │               ·                            │   ·                    │  ·          │    ·               │  ·                 │                                       · │  ·                         │               · │                     · │         ·               │              ·                  │
│               ·                │     · │   ·               │           ·            │            ·                                         │ ·                                     │   ·                  │    ·                  │       ·                   │                           · │  ·                   │   ·                       │               ·                            │   ·                    │  ·          │    ·               │  ·                 │                                       · │  ·                         │               · │                     · │         ·               │              ·                  │
│ 2023/06/12 3:56:57 PM GMT+5:30 │    23 │ Female            │ Multiple times a week  │ Beauty and Personal Care                             │ Sometimes                             │ Few times a month    │ categories            │ Multiple pages            │                           2 │ Maybe                │ Often                     │ Found a better price elsewhere             │ Often                  │ true        │ Moderately         │ Sometimes          │                                       3 │ Sometimes                  │               3 │                     5 │ Competitive prices      │ Customer service responsiveness │
│ 2023/06/12 3:57:52 PM GMT+5:30 │    23 │ Female            │ Once a week            │ Groceries and Gourmet Food                           │ Sometimes                             │ Few times a week     │ categories            │ Multiple pages            │                           3 │ Maybe                │ Rarely                    │ High shipping costs                        │ Always                 │ true        │ Moderately         │ Sometimes          │                                       4 │ Sometimes                  │               3 │                     4 │ Product recommendations │ Customer service responsiveness │
│ 2023/06/12 3:59:10 PM GMT+5:30 │    23 │ Female            │ Once a month           │ Beauty and Personal Care                             │ Sometimes                             │ Few times a week     │ categories            │ Multiple pages            │                           3 │ Maybe                │ Sometimes                 │ Found a better price elsewhere             │ Rarely                 │ true        │ Moderately         │ Sometimes          │                                       4 │ Sometimes                  │               3 │                     4 │ Product recommendations │ Product quality and accuracy    │
│ 2023/06/12 3:59:59 PM GMT+5:30 │    23 │ Female            │ Few times a month      │ Beauty and Personal Care                             │ Yes                                   │ Few times a week     │ Keyword               │ First page                │                           3 │ Maybe                │ Sometimes                 │ Found a better price elsewhere             │ Sometimes              │ true        │ Occasionally       │ Yes                │                                       3 │ Sometimes                  │               3 │                     4 │ Competitive prices      │ Customer service responsiveness │
│ 2023/06/12 4:00:56 PM GMT+5:30 │    25 │ Female            │ Once a week            │ Beauty and Personal Care                             │ Sometimes                             │ Multiple times a day │ categories            │ Multiple pages            │                           4 │ Maybe                │ Sometimes                 │ Found a better price elsewhere             │ Sometimes              │ true        │ Heavily            │ Sometimes          │                                       3 │ Sometimes                  │               3 │                     3 │ Product recommendations │ Customer service responsiveness │
│ 2023/06/12 4:02:02 PM GMT+5:30 │    23 │ Female            │ Once a week            │ Beauty and Personal Care                             │ Sometimes                             │ Few times a week     │ categories            │ Multiple pages            │                           4 │ Maybe                │ Sometimes                 │ Found a better price elsewhere             │ Sometimes              │ true        │ Moderately         │ Sometimes          │                                       3 │ Sometimes                  │               3 │                     4 │ Competitive prices      │ Customer service responsiveness │
│ 2023/06/12 4:02:53 PM GMT+5:30 │    23 │ Female            │ Once a week            │ Clothing and Fashion                                 │ Sometimes                             │ Few times a week     │ Filter                │ Multiple pages            │                           3 │ Maybe                │ Sometimes                 │ Found a better price elsewhere             │ Sometimes              │ true        │ Heavily            │ Sometimes          │                                       3 │ Sometimes                  │               3 │                     3 │ Product recommendations │ Reducing packaging waste        │
│ 2023/06/12 4:03:59 PM GMT+5:30 │    23 │ Female            │ Once a month           │ Beauty and Personal Care                             │ Sometimes                             │ Few times a week     │ categories            │ Multiple pages            │                           3 │ Maybe                │ Sometimes                 │ High shipping costs                        │ Sometimes              │ true        │ Occasionally       │ Sometimes          │                                       3 │ Sometimes                  │               2 │                     3 │ Wide product selection  │ Product quality and accuracy    │
│ 2023/06/12 9:57:20 PM GMT+5:30 │    23 │ Female            │ Few times a month      │ Beauty and Personal Care;Clothing and Fashion;others │ Yes                                   │ Few times a month    │ Keyword               │ Multiple pages            │                           1 │ Yes                  │ Often                     │ others                                     │ Sometimes              │ false       │ Heavily            │ Yes                │                                       2 │ Yes                        │               2 │                     2 │ Wide product selection  │ Product quality and accuracy    │
│ 2023/06/16 9:16:05 AM GMT+5:30 │    23 │ Female            │ Once a week            │ Clothing and Fashion                                 │ Sometimes                             │ Multiple times a day │ Keyword               │ Multiple pages            │                           3 │ Maybe                │ Often                     │ Found a better price elsewhere             │ Sometimes              │ true        │ Moderately         │ Sometimes          │                                       3 │ Sometimes                  │               3 │                     3 │ Product recommendations │ Product quality and accuracy    │
├────────────────────────────────┴───────┴───────────────────┴────────────────────────┴──────────────────────────────────────────────────────┴───────────────────────────────────────┴──────────────────────┴───────────────────────┴───────────────────────────┴─────────────────────────────┴──────────────────────┴───────────────────────────┴────────────────────────────────────────────┴────────────────────────┴─────────────┴────────────────────┴────────────────────┴─────────────────────────────────────────┴────────────────────────────┴─────────────────┴───────────────────────┴─────────────────────────┴─────────────────────────────────┤
│ 602 rows (20 shown)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            23 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [4]:
# We can transform the db result into Pandas Dataframe

df_db = db.df()
display(df_db)

,Timestamp,age,Gender,Purchase_Frequency,Purchase_Categories,Personalized_Recommendation_Frequency,Browsing_Frequency,Product_Search_Method,Search_Result_Exploration,Customer_Reviews_Importance,...,Saveforlater_Frequency,Review_Left,Review_Reliability,Review_Helpfulness,Personalized_Recommendation_Frequency_1,Recommendation_Helpfulness,Rating_Accuracy,Shopping_Satisfaction,Service_Appreciation,Improvement_Areas
0,2023/06/04 1:28:19 PM GMT+5:30,23,Female,Few times a month,Beauty and Personal Care,Yes,Few times a week,Keyword,Multiple pages,1,...,Sometimes,True,Occasionally,Yes,2,Yes,1,1,Competitive prices,Reducing packaging waste
1,2023/06/04 2:30:44 PM GMT+5:30,23,Female,Once a month,Clothing and Fashion,Yes,Few times a month,Keyword,Multiple pages,1,...,Rarely,False,Heavily,Yes,2,Sometimes,3,2,Wide product selection,Reducing packaging waste
2,2023/06/04 5:04:56 PM GMT+5:30,24,Prefer not to say,Few times a month,Groceries and Gourmet Food;Clothing and Fashion,No,Few times a month,Keyword,Multiple pages,2,...,Rarely,False,Occasionally,No,4,No,3,3,Competitive prices,Product quality and accuracy
3,2023/06/04 5:13:00 PM GMT+5:30,24,Female,Once a month,Beauty and Personal Care;Clothing and Fashion;...,Sometimes,Few times a month,Keyword,First page,5,...,Sometimes,True,Heavily,Yes,3,Sometimes,3,4,Competitive prices,Product quality and accuracy
4,2023/06/04 5:28:06 PM GMT+5:30,22,Female,Less than once a month,Beauty and Personal Care;Clothing and Fashion,Yes,Few times a month,Filter,Multiple pages,1,...,Rarely,False,Heavily,Yes,4,Yes,2,2,Competitive prices,Product quality and accuracy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
597,2023/06/12 4:02:02 PM GMT+5:30,23,Female,Once a week,Beauty and Personal Care,Sometimes,Few times a week,categories,Multiple pages,4,...,Sometimes,True,Moderately,Sometimes,3,Sometimes,3,4,Competitive prices,Customer service responsiveness
598,2023/06/12 4:02:53 PM GMT+5:30,23,Female,Once a week,Clothing and Fashion,Sometimes,Few times a week,Filter,Multiple pages,3,...,Sometimes,True,Heavily,Sometimes,3,Sometimes,3,3,Product recommendations,Reducing packaging waste
599,2023/06/12 4:03:59 PM GMT+5:30,23,Female,Once a month,Beauty and Personal Care,Sometimes,Few times a week,categories,Multiple pages,3,...,Sometimes,True,Occasionally,Sometimes,3,Sometimes,2,3,Wide product selection,Product quality and accuracy
600,2023/06/12 9:57:20 PM GMT+5:30,23,Female,Few times a month,Beauty and Personal Care;Clothing and Fashion;...,Yes,Few times a month,Keyword,Multiple pages,1,...,Sometimes,False,Heavily,Yes,2,Yes,2,2,Wide product selection,Product quality and accuracy
601,2023/06/16 9:16:05 AM GMT+5:30,23,Female,Once a week,Clothing and Fashion,Sometimes,Multiple times a day,Keyword,Multiple pages,3,...,Sometimes,True,Moderately,Sometimes,3,Sometimes,3,3,Product recommendations,Product quality and accuracy

In [5]:
# DuckDB can also read Pandas dataframes
db_df = duckdb.sql("SELECT * FROM df_db")
display(db_df)

┌────────────────────────────────┬───────┬───────────────────┬────────────────────────┬──────────────────────────────────────────────────────┬───────────────────────────────────────┬──────────────────────┬───────────────────────┬───────────────────────────┬─────────────────────────────┬──────────────────────┬───────────────────────────┬────────────────────────────────────────────┬────────────────────────┬─────────────┬────────────────────┬────────────────────┬─────────────────────────────────────────┬────────────────────────────┬─────────────────┬───────────────────────┬─────────────────────────┬─────────────────────────────────┐
│           Timestamp            │  age  │      Gender       │   Purchase_Frequency   │                 Purchase_Categories                  │ Personalized_Recommendation_Frequency │  Browsing_Frequency  │ Product_Search_Method │ Search_Result_Exploration │ Customer_Reviews_Importance │ Add_to_Cart_Browsing │ Cart_Completion_Frequency │          Cart_Abandonment_Factors          │ Saveforlater_Frequency │ Review_Left │ Review_Reliability │ Review_Helpfulness │ Personalized_Recommendation_Frequency_1 │ Recommendation_Helpfulness │ Rating_Accuracy │ Shopping_Satisfaction │  Service_Appreciation   │        Improvement_Areas        │
│            varchar             │ int64 │      varchar      │        varchar         │                       varchar                        │                varchar                │       varchar        │        varchar        │          varchar          │            int64            │       varchar        │          varchar          │                  varchar                   │        varchar         │   boolean   │      varchar       │      varchar       │                  int64                  │          varchar           │      int64      │         int64         │         varchar         │             varchar             │
├────────────────────────────────┼───────┼───────────────────┼────────────────────────┼──────────────────────────────────────────────────────┼───────────────────────────────────────┼──────────────────────┼───────────────────────┼───────────────────────────┼─────────────────────────────┼──────────────────────┼───────────────────────────┼────────────────────────────────────────────┼────────────────────────┼─────────────┼────────────────────┼────────────────────┼─────────────────────────────────────────┼────────────────────────────┼─────────────────┼───────────────────────┼─────────────────────────┼─────────────────────────────────┤
│ 2023/06/04 1:28:19 PM GMT+5:30 │    23 │ Female            │ Few times a month      │ Beauty and Personal Care                             │ Yes                                   │ Few times a week     │ Keyword               │ Multiple pages            │                           1 │ Yes                  │ Sometimes                 │ Found a better price elsewhere             │ Sometimes              │ true        │ Occasionally       │ Yes                │                                       2 │ Yes                        │               1 │                     1 │ Competitive prices      │ Reducing packaging waste        │
│ 2023/06/04 2:30:44 PM GMT+5:30 │    23 │ Female            │ Once a month           │ Clothing and Fashion                                 │ Yes                                   │ Few times a month    │ Keyword               │ Multiple pages            │                           1 │ Yes                  │ Often                     │ High shipping costs                        │ Rarely                 │ false       │ Heavily            │ Yes                │                                       2 │ Sometimes                  │               3 │                     2 │ Wide product selection  │ Reducing packaging waste        │
│ 2023/06/04 5:04:56 PM GMT+5:30 │    24 │ Prefer not to say │ Few times a month      │ Groceries and Gourmet Food;Clothing and Fashion      │ No                                    │ Few times a month    │ Keyword               │ Multiple pages            │                           2 │ Yes                  │ Sometimes                 │ Found a better price elsewhere             │ Rarely                 │ false       │ Occasionally       │ No                 │                                       4 │ No                         │               3 │                     3 │ Competitive prices      │ Product quality and accuracy    │
│ 2023/06/04 5:13:00 PM GMT+5:30 │    24 │ Female            │ Once a month           │ Beauty and Personal Care;Clothing and Fashion;others │ Sometimes                             │ Few times a month    │ Keyword               │ First page                │                           5 │ Maybe                │ Sometimes                 │ Found a better price elsewhere             │ Sometimes              │ true        │ Heavily            │ Yes                │                                       3 │ Sometimes                  │               3 │                     4 │ Competitive prices      │ Product quality and accuracy    │
│ 2023/06/04 5:28:06 PM GMT+5:30 │    22 │ Female            │ Less than once a month │ Beauty and Personal Care;Clothing and Fashion        │ Yes                                   │ Few times a month    │ Filter                │ Multiple pages            │                           1 │ Yes                  │ Sometimes                 │ High shipping costs                        │ Rarely                 │ false       │ Heavily            │ Yes                │                                       4 │ Yes                        │               2 │                     2 │ Competitive prices      │ Product quality and accuracy    │
│ 2023/06/04 6:01:59 PM GMT+5:30 │    21 │ Female            │ Less than once a month │ Clothing and Fashion                                 │ No                                    │ Rarely               │ categories            │ Multiple pages            │                           1 │ Yes                  │ Rarely                    │ Changed my mind or no longer need the item │ Never                  │ false       │ Heavily            │ Yes                │                                       5 │ No                         │               5 │                     2 │ Wide product selection  │ Product quality and accuracy    │
│ 2023/06/04 6:31:41 PM GMT+5:30 │    22 │ Female            │ Less than once a month │ Clothing and Fashion                                 │ No                                    │ Rarely               │ Filter                │ Multiple pages            │                           1 │ Yes                  │ Often                     │ High shipping costs                        │ Rarely                 │ false       │ Heavily            │ Yes                │                                       3 │ Sometimes                  │               3 │                     3 │ Wide product selection  │ Shipping speed and reliability  │
│ 2023/06/04 7:13:12 PM GMT+5:30 │    21 │ Female            │ Few times a month      │ Beauty and Personal Care;Clothing and Fashion        │ No                                    │ Rarely               │ Keyword               │ Multiple pages            │                           1 │ Yes                  │ Often                     │ Found a better price elsewhere             │ Rarely                 │ false       │ Heavily            │ Sometimes          │                                       3 │ Sometimes                  │               1 │                     3 │ Competitive prices      │ Shipping speed and reliability  │
│ 2023/06/04 7:23:21 PM GMT+5:30 │    20 │ Female            │ Less than once a month │ Beauty and Personal Care;Clothing and Fashion        │ Sometimes                             │ Few times a month    │ Keyword               │ First page                │                           1 │ Yes                  │ Sometimes                 │ Changed my mind or no longer need the item │ Often                  │ false       │ Moderately         │ Yes                │                                       2 │ Yes                        │               2 │                     2 │ Wide product selection  │ Reducing packaging waste        │
│ 2023/06/04 7:33:12 PM GMT+5:30 │    23 │ Female            │ Less than once a month │ Beauty and Personal Care;Clothing and Fashion        │ No                                    │ Rarely               │ Keyword               │ Multiple pages            │                           1 │ Yes                  │ Rarely                    │ Found a better price elsewhere             │ Rarely                 │ false       │ Heavily            │ Yes                │                                       3 │ Yes                        │               3 │                     4 │ Wide product selection  │ Product quality and accuracy    │
│               ·                │     · │   ·               │           ·            │            ·                                         │ ·                                     │   ·                  │    ·                  │       ·                   │                           · │  ·                   │   ·                       │               ·                            │   ·                    │  ·          │    ·               │  ·                 │                                       · │  ·                         │               · │                     · │         ·               │              ·                  │
│               ·                │     · │   ·               │           ·            │            ·                                         │ ·                                     │   ·                  │    ·                  │       ·                   │                           · │  ·                   │   ·                       │               ·                            │   ·                    │  ·          │    ·               │  ·                 │                                       · │  ·                         │               · │                     · │         ·               │              ·                  │
│               ·                │     · │   ·               │           ·            │            ·                                         │ ·                                     │   ·                  │    ·                  │       ·                   │                           · │  ·                   │   ·                       │               ·                            │   ·                    │  ·          │    ·               │  ·                 │                                       · │  ·                         │               · │                     · │         ·               │              ·                  │
│ 2023/06/12 3:56:57 PM GMT+5:30 │    23 │ Female            │ Multiple times a week  │ Beauty and Personal Care                             │ Sometimes                             │ Few times a month    │ categories            │ Multiple pages            │                           2 │ Maybe                │ Often                     │ Found a better price elsewhere             │ Often                  │ true        │ Moderately         │ Sometimes          │                                       3 │ Sometimes                  │               3 │                     5 │ Competitive prices      │ Customer service responsiveness │
│ 2023/06/12 3:57:52 PM GMT+5:30 │    23 │ Female            │ Once a week            │ Groceries and Gourmet Food                           │ Sometimes                             │ Few times a week     │ categories            │ Multiple pages            │                           3 │ Maybe                │ Rarely                    │ High shipping costs                        │ Always                 │ true        │ Moderately         │ Sometimes          │                                       4 │ Sometimes                  │               3 │                     4 │ Product recommendations │ Customer service responsiveness │
│ 2023/06/12 3:59:10 PM GMT+5:30 │    23 │ Female            │ Once a month           │ Beauty and Personal Care                             │ Sometimes                             │ Few times a week     │ categories            │ Multiple pages            │                           3 │ Maybe                │ Sometimes                 │ Found a better price elsewhere             │ Rarely                 │ true        │ Moderately         │ Sometimes          │                                       4 │ Sometimes                  │               3 │                     4 │ Product recommendations │ Product quality and accuracy    │
│ 2023/06/12 3:59:59 PM GMT+5:30 │    23 │ Female            │ Few times a month      │ Beauty and Personal Care                             │ Yes                                   │ Few times a week     │ Keyword               │ First page                │                           3 │ Maybe                │ Sometimes                 │ Found a better price elsewhere             │ Sometimes              │ true        │ Occasionally       │ Yes                │                                       3 │ Sometimes                  │               3 │                     4 │ Competitive prices      │ Customer service responsiveness │
│ 2023/06/12 4:00:56 PM GMT+5:30 │    25 │ Female            │ Once a week            │ Beauty and Personal Care                             │ Sometimes                             │ Multiple times a day │ categories            │ Multiple pages            │                           4 │ Maybe                │ Sometimes                 │ Found a better price elsewhere             │ Sometimes              │ true        │ Heavily            │ Sometimes          │                                       3 │ Sometimes                  │               3 │                     3 │ Product recommendations │ Customer service responsiveness │
│ 2023/06/12 4:02:02 PM GMT+5:30 │    23 │ Female            │ Once a week            │ Beauty and Personal Care                             │ Sometimes                             │ Few times a week     │ categories            │ Multiple pages            │                           4 │ Maybe                │ Sometimes                 │ Found a better price elsewhere             │ Sometimes              │ true        │ Moderately         │ Sometimes          │                                       3 │ Sometimes                  │               3 │                     4 │ Competitive prices      │ Customer service responsiveness │
│ 2023/06/12 4:02:53 PM GMT+5:30 │    23 │ Female            │ Once a week            │ Clothing and Fashion                                 │ Sometimes                             │ Few times a week     │ Filter                │ Multiple pages            │                           3 │ Maybe                │ Sometimes                 │ Found a better price elsewhere             │ Sometimes              │ true        │ Heavily            │ Sometimes          │                                       3 │ Sometimes                  │               3 │                     3 │ Product recommendations │ Reducing packaging waste        │
│ 2023/06/12 4:03:59 PM GMT+5:30 │    23 │ Female            │ Once a month           │ Beauty and Personal Care                             │ Sometimes                             │ Few times a week     │ categories            │ Multiple pages            │                           3 │ Maybe                │ Sometimes                 │ High shipping costs                        │ Sometimes              │ true        │ Occasionally       │ Sometimes          │                                       3 │ Sometimes                  │               2 │                     3 │ Wide product selection  │ Product quality and accuracy    │
│ 2023/06/12 9:57:20 PM GMT+5:30 │    23 │ Female            │ Few times a month      │ Beauty and Personal Care;Clothing and Fashion;others │ Yes                                   │ Few times a month    │ Keyword               │ Multiple pages            │                           1 │ Yes                  │ Often                     │ others                                     │ Sometimes              │ false       │ Heavily            │ Yes                │                                       2 │ Yes                        │               2 │                     2 │ Wide product selection  │ Product quality and accuracy    │
│ 2023/06/16 9:16:05 AM GMT+5:30 │    23 │ Female            │ Once a week            │ Clothing and Fashion                                 │ Sometimes                             │ Multiple times a day │ Keyword               │ Multiple pages            │                           3 │ Maybe                │ Often                     │ Found a better price elsewhere             │ Sometimes              │ true        │ Moderately         │ Sometimes          │                                       3 │ Sometimes                  │               3 │                     3 │ Product recommendations │ Product quality and accuracy    │
├────────────────────────────────┴───────┴───────────────────┴────────────────────────┴──────────────────────────────────────────────────────┴───────────────────────────────────────┴──────────────────────┴───────────────────────┴───────────────────────────┴─────────────────────────────┴──────────────────────┴───────────────────────────┴────────────────────────────────────────────┴────────────────────────┴─────────────┴────────────────────┴────────────────────┴─────────────────────────────────────────┴────────────────────────────┴─────────────────┴───────────────────────┴─────────────────────────┴─────────────────────────────────┤
│ 602 rows (20 shown)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            23 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

### DuckDB vs SQLite for Database Creation

In [6]:
import sqlite3

In [ ]:
connection = sqlite3.connect('/Users/julianasampar/Desktop/learning_dev/personal_dev/pyprojects/dbt_database.db')
cursor = connection.cursor()

cursor.execute("SELECT * FROM dim_films LIMIT 1")
print(cursor.fetchall())

connection.commit()
cursor.close()
connection.close()

OperationalError: no such table: dim_films

In [16]:
connection = duckdb.connect('dbt_database.db')
connection.sql("CREATE OR REPLACE TABLE int_rentals (id INT)")
print(connection.sql("SELECT * FROM int_rentals"))
connection.commit()
connection.close()

┌────────┐
│   id   │
│ int32  │
├────────┤
│ 0 rows │
└────────┘